title: William Barkoff

collections:
  projects:
    output: true
    permalink: /projects/:name

footer-social:
  - icon: fa-twitter
    url: https://twitter.com/nywillb
  - icon: fa-github
    url: https://github.com/nywillb