title: Will Barkoff
tagline: I'm Will Barkoff, a student by day and a developer by night. I'm indecisive at dusk.

collections:
  projects:
    output: true
    permalink: /projects/:name

footer-social:
  - icon: fa-twitter
    url: https://twitter.com/willbarkoff
    username: "@willbarkoff"
  - icon: fa-github
    url: https://github.com/willbarkoff
    username: "@willbarkoff"
  - icon: fa-key
    url: /key.html
    username: "PGP Key"

footer-projects:
  - name: MyHomeworkSpace
    url: https://myhomework.space
  - name: Honor with Code
    url: https://honorwithcode.org

footer-resources:
  - name: Website Source Code
    url: https://github.com/willbarkoff/willbarkoff.github.io
  - name: Contact Me
    url: /contact.html
  - name: PGP Key
    url: /key.html

repository: "willbarkoff/willbarkoff.github.io"

permalink: /:categories/:year/:month/:day/:title

plugins:
  - jemoji
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-feed
